// import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Headr";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
// import { ClerkProvider } from "@clerk/nextjs";
import {Inter} from "next/font/google" 
import { Toaster } from "sonner";
export const metadata = {
  title: "Sensai - AI Career Coach",
  description: "Generated by create next app",
};
const inter = Inter({subsets:['latin']})

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme :dark
    }}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}}`}
        >
       <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            >
            {/* header */}
            <Header />
            {/*  */}
            <main className="min-h-screen space-y-10">
           
            {children}
            </main>
            <Toaster richColors/>

            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made with  ❤️ by Nutan</p>
              </div>
            </footer>
            {/* footer */}
          </ThemeProvider>
      </body>
    </html>
            </ClerkProvider>
  );
}
